inference:
  model_path: /gpfs/data/abl/home/shenkn01/Reizis_mm10/c-origami-tool/src/training/runs/Patski_mm10_2022-05-19T14:40:52.934896/state_dict_73.pt
  input_folder: /gpfs/data/abl/home/shenkn01/hic_prediction/evaluation/data/mouse/Patski/processed_data
  ctcf_name: peaks.bigwig
  atac_name: 4DNFINU4WSEY.bw
  chr_lengths: chr_length.json
  chr_fa_path: /gpfs/data/abl/home/shenkn01/hic_prediction/evaluation/data/mouse/Patski/raw_data
  cell_line: Patski
  chr_num: 2
  start_pos: 75000000
  task: screening # choose between predict or perturbation or screening

#Perturbation only configs
  del_pos: 
    - start: 75500000
      end: 76000000
    - start: 76500000
      end: 76900000

#Screening only configs
  end_pos: 77097152       # optional (default is to screen 2 MB from the start pos)
  del_window: 500         # how many base pairs to remove
  step_size: 100          # how far each deletion is from the next

