model_path:
input_folder:
ctcf_name: ctcf_log2fc.bw
atac_name: atac.bw
chr_fa_path:
chr_lengths: chr_length.json
cell_line: Patski # Add cell line name
chr_num: 1
start_pos: 0
task: prediction # choose between predict or perturbation or screening

#Perturbation only configs
del_pos: 
  - start: 
    end: 
  - start: 
    end:

#Screening only configs
end_pos:       # optional (default is to screen 2 MB from the start pos)
del_window:    # how many base pairs to remove
step_size:     # how far each deletion is from the next

