# Default config file

defaults:
    - _self_
    - dataset: default
    - model: ConvTransModel
    - optim: transformer_optim

run:
    name: 'c-origami'
    save_root: /gpfs/data/tsirigoslab/home/jt3545/hic_prediction
    save_path: &run_dir ${run.save_root}/C.Origami/src/training/runs/${run.name}/${now:%Y-%m-%d}/${now:%H-%M-%S-%f}
    mode: 'train'
    debug: FALSE
    seed: 2077

hydra:
    run:
        dir: *run_dir

logger:
    wandb:
        mode: 'online'
        project: 'C-Origami'

dataloader:
    batch_size: 8
    ddp_enabled: TRUE
    num_gpu: 4
    num_workers: 12
    pin_memory: TRUE
    prefetch_factor: 4

trainer:
    max_epochs: 200
    patience: 40
    save_top_n: 20
    num_gpu: 4
